"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = require("react");
require("./index.css");
var STARS = '76k+'; // NOTE: this line is generated by src/generate.js. Do not change!
var StarButton = function (_a) {
    var owner = _a.owner, repo = _a.repo;
    if (!repo)
        throw new Error('repo is required');
    return (<span className="github-btn github-stargazers github-btn-large">
            <a className="gh-btn" href={"https://github.com/".concat(owner, "/").concat(repo)} rel="noopener noreferrer" target="_blank" aria-label={"Star ".concat(owner, "/").concat(repo, " on GitHub")}>
                <span className="gh-ico" aria-hidden="true"></span>
                <span className="gh-text">Star</span>
            </a>
            <a className="gh-count" href={"https://github.com/".concat(owner, "/").concat(repo, "/stargazers")} rel="noopener noreferrer" target="_blank" aria-label={"".concat(STARS, " stargazers on GitHub")} style={{ display: 'block' }}>
                {STARS}
            </a>
        </span>);
};
exports.default = StarButton;
